version: "3.9"

    
services:
   dev_app:
      image: "payments:latest"
      ports:
         - "0.0.0.0:9099:9099/tcp"
      environment:
         - spring.mail.host=${SMTP_SERVER}
         - spring.mail.username=${SMTP_USER}
         - spring.mail.password=${SMTP_PASSWORD}
         - spring.mail.port=465