version: "3.9"

    
services:
   dev_app:
      image: "payments:latest"
      ports:
         - "0.0.0.0:9099:9099/tcp"
      environment:
         - spring.mail.host=smtp.test
         - spring.mail.port=43