version: "3.9"

    
services:
   dev_app:
      image: "payments:latest"
      ports:
         - "0.0.0.0:9099:9099/tcp"
      configs:
        - source: dev-config
          target: /application.properties
          uid: '103'
          gid: '103'
          mode: 0440