
name: Deploy dev environment job.

on:
  workflow_dispatch:

jobs:
  deploy_dev:
    runs-on: ln-moni01

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Set up MVN
      run: echo "/opt/apache-maven-3.8.4/bin" >> $GITHUB_PATH
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build docker image
      run: docker build . -t payments:latest
    - name: Deploy docker config
      run: docker config create dev-hosted config/dev-hosted.properties
    - name: Deploy docker service
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: docker-compose up -d --build --force-recreate
