name: Deploy dev environment job.(OnPrem)

on:
  workflow_dispatch:

jobs:
  deploy_dev:
    runs-on: ln-moni01

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Set up MVN
      run: echo "/opt/apache-maven-3.8.4/bin" >> $GITHUB_PATH
    - name: Get last version
      run: . ./getVersion.sh
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build docker image
      run: docker build . -t payments:latest
    - name: Tag version
      run: ./tagRepo.sh
    - name: Deploy docker service
      run: docker stack deploy --compose-file docker-compose.yml test
