name: Package the app and create new version

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Get last version
      run: . ./getVersion.sh
    - name: Get last version
      run: echo ${{env.NEXT_TAG }}