name: Package the app and create new version

on:
  workflow_dispatch:

jobs:
  create-new-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Get last version
      run: ./getVersion.sh
    - name: Set Maven version
      run: mvn versions:set -DnewVersion=$env.NEXT_TAG
    - name: Build with Maven
      run: mvn -B package --file pom.xml 
    - name: Creating tag
      run: ./tagRepo.sh